name: Pull Request

on:
  pull_request:
  workflow_dispatch:

jobs:
  geth:
    strategy:
      matrix:
        settings:
          - arch: linux/amd64
            runs-on: ubuntu-24.04
          - arch: linux/arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.settings.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: geth/Dockerfile
          push: false
          platforms: ${{ matrix.settings.arch }}

  reth:
    strategy:
      matrix:
        settings:
          - arch: linux/amd64
            runs-on: ubuntu-24.04
            features: jemalloc,asm-keccak,optimism
          - arch: linux/arm64
            runs-on: ubuntu-24.04-arm
            features: jemalloc,optimism
    runs-on: ${{ matrix.settings.runs-on}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: reth/Dockerfile
          push: false
          build-args: |
            FEATURES=${{ matrix.settings.features }}
          platforms: ${{ matrix.settings.arch }}

  nethermind:
    strategy:
      matrix:
        settings:
          - arch: linux/amd64
            runs-on: ubuntu-24.04
          - arch: linux/arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.settings.runs-on}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: nethermind/Dockerfile
          push: false
          platforms: ${{ matrix.settings.arch }}
